title: "Matej Martinović"
tagline: "Software Development Portfolio"

description: >-
  Software development portfolio focused on backend development,
  Python, C#/.NET, SQL, APIs, automation, data and GIS.

url: "https://1244Matt1244.github.io"
baseurl: ""

github:
  username: 1244Matt1244

social:
  name: "Matej Martinović"
  links:
    - "https://github.com/1244Matt1244"
    - "https://www.linkedin.com/in/matejmartinovic"

remote_theme: jekyll-theme-chirpy

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
highlighter: rouge

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - package.json
  - package-lock.json

