name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up Ruby environment
      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7  # Must match Gemfile
          bundler-cache: true

      # Step 3: Cache gems to speed up subsequent builds
      - name: Cache Gems
        uses: actions/cache@v3
        with:
          path: vendor/b
